spring.application.name=alertas-medicas
server.port=8080
# spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/5497f70a-565c-40b7-92c7-b62049f8638f/v2.0
logging.level.org.springframework.web: DEBUG
spring.datasource.url=jdbc:oracle:thin:@healzjhb0k6m53n7_high?TNS_ADMIN=./Wallet_HEALZJHB0K6M53N7
spring.datasource.username=ADMIN    
spring.datasource.password=Tardigrado13.
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.kafka.bootstrap-servers=localhost:29092,localhost:39092,localhost:49092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.topic.alertas=alertas
spring.kafka.topic.seniales_vitales=seniales_vitales

